// src/views/Parham.vue
<template>
  <div>
    <main class="container profile">
      <section>
        <router-link to="/">
          <span> &lt;&lt;back home </span>
        </router-link>
        <p>
          Seasoned Backend Engineer adept at designing and implementing <b>scalable</b> server <b>architectures</b>. Skilled in
          <b>Node JS</b>, database management, and <b>API development</b> to ensure optimal <b>performance</b> and reliability. A
          results-oriented professional committed to delivering efficient backend solutions for complex applications.
        </p>
        <h3>Technologies:</h3>
        <h6>Nest.js</h6>
        <h6>Docker</h6>
        <h6>Git</h6>
        <h6>Microservices</h6>
        <h3>Full CV:</h3>
        <a
          href="../../ParhamSaeednia.pdf"
          class="button"
          target="_blank"
          >Download</a
        >
      </section>
    </main>
    <footer>
      <ul>
        <a
          href="https://github.com/parhamsaeednia"
          target="_blank"
        >
          <li>Github</li>
        </a>
        <a
          href="https://www.linkedin.com/in/parham-saeednia-a88a30196/"
          target="_blank"
        >
          <li>linkedin</li>
        </a>
        <a
          href="mailto:saeedniaparham@gmail.com"
          target="_blank"
        >
          <li>mail</li>
        </a>
      </ul>
    </footer>
  </div>
</template>

<style scoped>
  div {
    position: relative;
  }

  .profile {
    min-height: calc(100dvh - var(--nav-space) - 64px);
    display: grid;
    align-items: center;
    grid-template-columns: 1fr;
    gap: clamp(16px, 3vw, 32px);
    padding-block: 0;
    background: #fafafa;
    z-index: 2;
  }

  .image-container {
    padding-right: 56px;
  }

  section {
    display: flex;
    flex-direction: column;
    border-left: 2px dashed #212121;
    padding-left: clamp(16px, 2vw, 40px);
  }

  p {
    text-align: justify;
  }

  span {
    line-height: 4em;
    font-weight: 500;
  }

  span:hover {
    cursor: pointer;
  }

  h3 {
    font-size: clamp(18px, 2.2vw, 26px);
    font-weight: 200;
    margin: 1em 0;
  }

  h6 {
    font-size: clamp(14px, 1.6vw, 16px);
  }

  a.button {
    border: 1px solid #212121;
    padding: 6px;
    background-color: #fafafa;
    cursor: pointer;
    font-family: "Montserrat", sans-serif;
    font-synthesis: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-transform: uppercase;
    width: fit-content;
    font-weight: 500;
  }

  footer {
    width: 100%;
    position: fixed;
    bottom: 0;
    z-index: 9;
    height: 64px;
    background: #fafafa;
  }

  ul {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  li {
    list-style: none;
    padding: 0 24px;
    font-size: clamp(14px, 1.6vw, 16px);
    font-weight: 300;
  }

  li:hover {
    font-weight: 500;
    cursor: pointer;
  }

  @media screen and (max-width: 1024px) {
    img {
      width: 100px;
    }

    .image-container {
      display: none;
    }

    span {
      font-size: small;
    }

    p {
      font-size: 12px;
    }

    a.button {
      font-size: small;
    }
  }
</style>

// app/parham/page.tsx
import Link from "next/link";
import styles from "./page.module.css";

export const metadata = {
  title: "Parham Saeednia – Backend Engineer",
  description:
    "Seasoned backend engineer experienced in scalable server architectures, Node.js, and API development.",
};

export default function ParhamPage() {
  return (
    <div className={styles.wrapper}>
      <main className={`container ${styles.profile}`}>
        <h1 className="visually-hidden">Parham Saeednia – Backend Engineer</h1>
        <section>
          <Link href="/">
            <span>&lt;&lt; Back Home</span>
          </Link>
          <p>
            Seasoned Backend Engineer adept at designing and implementing <b>scalable</b> server <b>architectures</b>.
            Skilled in <b>Node.js</b>, database management, and <b>API development</b> to ensure optimal <b>performance</b> and
            reliability. A results-oriented professional committed to delivering efficient backend solutions for complex
            applications.
          </p>
          <h3>Technologies:</h3>
          <h6>Nest.js</h6>
          <h6>Docker</h6>
          <h6>Git</h6>
          <h6>Microservices</h6>
          <h3>Full CV:</h3>
          <a href="/ParhamSaeednia.pdf" className={styles.button} target="_blank" rel="noopener noreferrer">
            Download
          </a>
        </section>
      </main>
      <footer className={styles.footer}>
        <ul className={styles.footerList}>
          <li className={styles.footerItem}>
            <a href="https://github.com/parhamsaeednia" target="_blank" rel="noopener noreferrer">
              Github
            </a>
          </li>
          <li className={styles.footerItem}>
            <a
              href="https://www.linkedin.com/in/parham-saeednia-a88a30196/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Linkedin
            </a>
          </li>
          <li className={styles.footerItem}>
            <a href="mailto:saeedniaparham@gmail.com" target="_blank" rel="noopener">
              Mail
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
}
